[package]
name = "rudelblinken-filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
enumflags2 = "0.7.10"
thiserror = "2.0.0"
zerocopy = { version = "0.8.7", features = ["derive"] }
