[package]
name = "rudelblinken-filesystem"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "2.0.3"
zerocopy = { version = "0.8.10", features = ["derive"] }

[features]
default = []
simulated = []
esp32 = []
