[workspace]
resolver = "2"

members = ["rudelblinken-firmware", "rudelblinken-cli", "rudelblinken-wasm"]

[profile.release]
opt-level = "s"
lto = "fat"
panic = "abort"

[profile.release.package.rudelblinken-wasm]
codegen-units = 1

[profile.dev]
debug = true
opt-level = "z"
