[build]
target = "wasm32-unknown-unknown"
# tiny stack, otherwise allocation during wasm runtime init fails
# 131072 (128 KiB) fails
#  98304  (96 KiB) fails (with an 128KiB alloc)
#  65536  (64 KiB) works
#  32768  (32 KiB) works
#  16384  (16 KiB) works
#   8192  (16 KiB) works
#   1024   (1 KiB) works
rustflags = ["-C", "link-args=-zstack-size=16384"]

[target.wasm32-unknown-unknown]
runner = [
    "sh",
    "-c",
    "cd $(dirname $(cargo locate-project --message-format plain))/../rudelblinken-cli && cargo run -- emulate $(test -f $0 && echo $0 || echo ../rudelblinken-wasm/$0)",
] # Run the wasm binary with the emulator


[unstable]
build-std = ["std", "panic_abort"]
